version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - misspell
    - revive
  exclusions:
    presets:
      - comments
      - std-error-handling
    rules:
      - path: _test\.go
        linters:
          - errcheck
      - source: "defer.*\\.Sync\\("
        linters:
          - errcheck
  settings:
    revive:
      rules:
        - name: exported
          severity: warning

formatters:
  enable:
    - gofmt
    - goimports
