version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - misspell
    - revive
  settings:
    revive:
      rules:
        - name: exported
          severity: warning

formatters:
  enable:
    - gofmt
    - goimports
